case pcode___treeview___treeview1:{ getParam(v, m, n); pp = new kb_treeview(0); myStack->pushParameter(pcode___treeview, pp); ((kb_treeview *) pp)->setInterpreter(this); break; }
case pcode___treeview___treeview:{ getParam(v, m, n); pp = new kb_treeview(v[0]->to_form()); myStack->pushParameter(pcode___treeview, pp); ((kb_treeview *) pp)->setInterpreter(this); break; }

                                 
case pcode___treeview__SETPROPERTY_SQL:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_SQL(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_SQL:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_SQL()); if (bReturn) pushStack(p); else delete p; break; }
 
case pcode___treeview__SETPROPERTY_MouseTracking:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_MouseTracking(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_MouseTracking:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_MouseTracking()); if (bReturn) pushStack(p); else delete p; break; }
 
                                
case pcode___treeview__SETPROPERTY_CursorAnimation:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_CursorAnimation(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_CursorAnimation:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_CursorAnimation()); if (bReturn) pushStack(p); else delete p; break; }

case pcode___treeview__METHOD_DataIds:{   
  
  getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); 
   
  QList<QByteArray> l = q->dynamicPropertyNames();
  
  _strings *ss = new _strings();

  foreach(QByteArray a, l)
  {
    QString s = QString::fromUtf8(a);
    if (s.compare("__kb1979.ControlType.kb__", Qt::CaseSensitive) != 0){
      ss->METHOD_Append(s);
    }
  }

  interpreter_parameter *p = new interpreter_parameter(ss); 
    
  if (bReturn) pushStack(p); else delete p; break; 
}

case pcode___treeview__METHOD_DataRemove:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataRemove(v[0]->toQString()); break; }
case pcode___treeview__METHOD_DataRemoveAll:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataRemoveAll(); break; }
case pcode___treeview__METHOD_DataSetBoolean:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataSetBoolean(v[0]->toQString(), v[1]->tot_boolean()); break; }
case pcode___treeview__METHOD_DataSetInteger:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataSetInteger(v[0]->toQString(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_DataSetString:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataSetString(v[0]->toQString(), v[1]->toQString()); break; }
case pcode___treeview__METHOD_DataSetDouble:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataSetDouble(v[0]->toQString(), v[1]->tot_double()); break; }
case pcode___treeview__METHOD_DataSetLong:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataSetLong(v[0]->toQString(), v[1]->tot_long()); break; }
case pcode___treeview__METHOD_DataSetDecimal:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataSetDecimal(v[0]->toQString(), v[1]->toDecimal()); break; }
case pcode___treeview__METHOD_DataSetDateTime:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_DataSetDateTime(v[0]->toQString(), v[1]->totDateTime()); break; }

case pcode___treeview__METHOD_DataBoolean:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_DataBoolean(v[0]->toQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_DataInteger:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_DataInteger(v[0]->toQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_DataString:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_DataString(v[0]->toQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_DataDouble:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_DataDouble(v[0]->toQString())); if (bReturn) pushStack(p); else delete p; break; }

case pcode___treeview__METHOD_DataLong:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_DataLong(v[0]->toQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_DataDecimal:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_DataDecimal(v[0]->toQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_DataDateTime:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_DataDateTime(v[0]->toQString())); if (bReturn) pushStack(p); else delete p; break; }


case pcode___treeview__METHOD_ClearFocus:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ClearFocus(); break; }
case pcode___treeview__METHOD_ToggleVisible:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ToggleVisible(); break; }
case pcode___treeview__METHOD_SingleShot:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SingleShot(v[0]->tot_integer()); break; }
case pcode___treeview__METHOD_StartTimer:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_StartTimer(); break; }
case pcode___treeview__METHOD_StopTimer:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_StopTimer(); break; }

case pcode___treeview__METHOD_LocalX:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_LocalX(v[0]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_LocalY:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_LocalY(v[0]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }

case pcode___treeview__METHOD_GlobalX:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_GlobalX(v[0]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_GlobalY:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_GlobalY(v[0]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }

case pcode___treeview__METHOD_UnderMouse:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter(q->METHOD_UnderMouse()); if (bReturn) pushStack(p); else delete p; break; }

case pcode___treeview__SETPROPERTY_Mask:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Mask(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_Mask:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_Mask()); if (bReturn) pushStack(p); else delete p; break; }
                         
case pcode___treeview__SETPROPERTY_SoundOnEvent:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_SoundOnEvent(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_SoundOnEvent:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_SoundOnEvent()); if (bReturn) pushStack(p); else delete p; break; }

case pcode___treeview__SETPROPERTY_Left:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_X(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_Left:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview();  i = q->GETPROPERTY_X(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_Top:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Y(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_Top:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview();  i =  q->GETPROPERTY_Y(); if (bReturn) pushStackInteger(i); break; }

case pcode___treeview__SETPROPERTY_LocalX:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_X(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_LocalX:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview();  i = q->GETPROPERTY_X(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_LocalY:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Y(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_LocalY:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview();  i =  q->GETPROPERTY_Y(); if (bReturn) pushStackInteger(i); break; }

case pcode___treeview__SETPROPERTY_DrawOnPaint:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_DrawOnPaint(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_DrawOnPaint:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_DrawOnPaint()); if (bReturn) pushStack(p); else delete p; break; }
                    
case pcode___treeview__SETPROPERTY_Palette:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Palette(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_Palette:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_Palette()); if (bReturn) pushStack(p); else delete p; break; }
                         
case pcode___treeview__SETPROPERTY_BackgroundStyle:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_BackgroundStyle(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_BackgroundStyle:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_BackgroundStyle()); if (bReturn) pushStack(p); else delete p; break; }
                         

case pcode___treeview__SETPROPERTY_RootIsDecorated:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_RootIsDecorated(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_RootIsDecorated:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_RootIsDecorated()); if (bReturn) pushStack(p); else delete p; break; }

case pcode___treeview__SETPROPERTY_SelectionMode:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_SelectionMode(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_SelectionMode:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_SelectionMode()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_AlternatingRowColors:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_AlternatingRowColors(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_AlternatingRowColors:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_AlternatingRowColors()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_AppendChild:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_AppendChild(v[0]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_AppendChild1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_AppendChild(v[0]->toConstQString(), v[1]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_AppendChild2:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_AppendChild(v[0]->tot_long(), v[1]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_AppendChild3:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_AppendChild(v[0]->tot_long(), v[1]->toConstQString(), v[2]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_ChildCount:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_ChildCount(v[0]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_Child:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Child(v[0]->tot_long(), v[1]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_Tag:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Tag(v[0]->tot_long(), v[1]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetTag:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetTag(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_CheckState:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_CheckState(v[0]->tot_long(), v[1]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetCheckState:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetCheckState(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_Data:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Data(v[0]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_Flag:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Flag(v[0]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetFlag:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetFlag(v[0]->tot_long(), v[1]->toConstQString()); break; }
case pcode___treeview__METHOD_SetBackground:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetBackground(v[0]->tot_long(), v[1]->toInteger(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_SetBackground1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetBackground(v[0]->tot_long(), v[1]->toInteger(), v[2]->toConstQString(), v[3]->toConstQString()); break; }
case pcode___treeview__METHOD_SetFontColor:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetFontColor(v[0]->tot_long(), v[1]->toInteger(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_SetFontColor1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetFontColor(v[0]->tot_long(), v[1]->toInteger(), v[2]->toConstQString(), v[3]->toConstQString()); break; }
case pcode___treeview__METHOD_SetFont:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetFont(v[0]->tot_long(), v[1]->toInteger(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_Caption:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Caption(v[0]->tot_long(), v[1]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetCaption:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetCaption(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_SetIcon:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetIcon(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_IndexOfChild:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IndexOfChild(v[0]->tot_long(), v[1]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_InsertChild:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_InsertChild(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_InsertChild1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_InsertChild(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString(), v[3]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_IsExpanded:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IsExpanded(v[0]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetExpanded:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetExpanded(v[0]->tot_long(), v[1]->tot_boolean()); break; }
case pcode___treeview__METHOD_IsHidden:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IsHidden(v[0]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetHidden:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetHidden(v[0]->tot_long(), v[1]->tot_boolean()); break; }
case pcode___treeview__METHOD_IsSelected:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IsSelected(v[0]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetSelected:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetSelected(v[0]->tot_long(), v[1]->tot_boolean()); break; }
case pcode___treeview__METHOD_StatusTip:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_StatusTip(v[0]->tot_long(), v[1]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetStatusTip:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetStatusTip(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_ToolTip:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_ToolTip(v[0]->tot_long(), v[1]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetToolTip:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetToolTip(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_RemoveChild:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_RemoveChild(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_TextAlignment:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_TextAlignment(v[0]->tot_long(), v[1]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetTextAlignment:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetTextAlignment(v[0]->tot_long(), v[1]->tot_integer(), v[2]->toConstQString()); break; }
case pcode___treeview__METHOD_ColumnCount:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_ColumnCount(v[0]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_Append:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Append(v[0]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_Append1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Append(v[0]->toConstQString(), v[1]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_ClosePersistentEditor:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ClosePersistentEditor(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_ColumnCount1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_ColumnCount()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_CurrentColumn:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_CurrentColumn()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_CurrentItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_CurrentItem()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_EditItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_EditItem(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_FindItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_FindItem(v[0]->toConstQString(), v[1]->toConstQString(), v[2]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_HeaderItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_HeaderItem()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_IndexOfTopLevelItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IndexOfTopLevelItem(v[0]->tot_long())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_Insert:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Insert(v[0]->tot_integer(), v[1]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_Insert1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_Insert(v[0]->tot_integer(), v[1]->toConstQString(), v[2]->toConstQString())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_InvisibleRootItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_InvisibleRootItem()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_ItemAt:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_ItemAt(v[0]->tot_integer(), v[1]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_OpenPersistentEditor:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_OpenPersistentEditor(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_FirstSelectedItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_FirstSelectedItem()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_NextSelectedItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_NextSelectedItem()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetColumnCount:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetColumnCount(v[0]->tot_integer()); break; }
case pcode___treeview__METHOD_SetCurrentItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetCurrentItem(v[0]->tot_long()); break; }
case pcode___treeview__METHOD_SetCurrentItem1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetCurrentItem(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_SetHeaderLabel:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetHeaderLabel(v[0]->toConstQString()); break; }
case pcode___treeview__METHOD_SetHeaderLabel1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetHeaderLabel(v[0]->toConstQString(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_SortColumn:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_SortColumn()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SortItems:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SortItems(v[0]->tot_integer(), v[1]->tot_boolean()); break; }
case pcode___treeview__METHOD_RemoveTopLevelItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_RemoveTopLevelItem(v[0]->tot_integer()); break; }
case pcode___treeview__METHOD_TopLevelItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_TopLevelItem(v[0]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_TopLevelItemCount:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_TopLevelItemCount()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_IsColumnHidden:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IsColumnHidden(v[0]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetColumnHidden:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetColumnHidden(v[0]->tot_integer(), v[1]->tot_boolean()); break; }
case pcode___treeview__METHOD_IsSortingEnabled:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IsSortingEnabled()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetSortingEnabled:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetSortingEnabled(v[0]->tot_boolean()); break; }
case pcode___treeview__METHOD_IsItemsExpandable:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IsItemsExpandable()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetItemsExpandable:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetItemsExpandable(v[0]->tot_boolean()); break; }
case pcode___treeview__METHOD_IsAllColumnsShowFocus:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IsAllColumnsShowFocus()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetAllColumnsShowFocus:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetAllColumnsShowFocus(v[0]->tot_boolean()); break; }
case pcode___treeview__METHOD_ColumnWidth:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_ColumnWidth(v[0]->tot_integer())); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetColumnWidth:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetColumnWidth(v[0]->tot_integer(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_CollapseAll:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_CollapseAll(); break; }
case pcode___treeview__METHOD_ExpandAll:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ExpandAll(); break; }
case pcode___treeview__METHOD_SelectAll:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SelectAll(); break; }
case pcode___treeview__METHOD_ShowColumn:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ShowColumn(v[0]->tot_integer()); break; }
case pcode___treeview__METHOD_CollapseItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_CollapseItem(v[0]->tot_long()); break; }
case pcode___treeview__METHOD_ExpandItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ExpandItem(v[0]->tot_long()); break; }
case pcode___treeview__METHOD_ScrollToItem:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ScrollToItem(v[0]->tot_long()); break; }
case pcode___treeview__METHOD_IsAlternatingRowColors:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->METHOD_IsAlternatingRowColors()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_SetAlternatingRowColors:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetAlternatingRowColors(v[0]->tot_boolean()); break; }
case pcode___treeview__METHOD_ScrollToBottom:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ScrollToBottom(); break; }
case pcode___treeview__METHOD_ScrollToTop:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_ScrollToTop(); break; }
case pcode___treeview__EVENT_CurrentItemChanged:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_CurrentItemChanged(v[0]->tot_long(), v[1]->tot_long()); break; }
case pcode___treeview__EVENT_ItemActivated:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemActivated(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__EVENT_ItemChanged:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemChanged(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__EVENT_ItemClicked:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemClicked(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__EVENT_ItemCollapsed:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemCollapsed(v[0]->tot_long()); break; }
case pcode___treeview__EVENT_ItemDoubleClicked:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemDoubleClicked(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__EVENT_ItemEntered:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemEntered(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__EVENT_ItemExpanded:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemExpanded(v[0]->tot_long()); break; }
case pcode___treeview__EVENT_ItemPressed:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemPressed(v[0]->tot_long(), v[1]->tot_integer()); break; }
case pcode___treeview__EVENT_ItemSelectionChanged:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->EVENT_ItemSelectionChanged(); break; }

case pcode___treeview__SETPROPERTY_Layout:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Layout(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_Layout:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_Layout()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__METHOD_Move:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Move(v[0]->tot_integer(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_Resize:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Resize(v[0]->tot_integer(), v[1]->tot_integer()); break; }
case pcode___treeview__METHOD_Show:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Show(); break; }
case pcode___treeview__METHOD_Hide:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Hide(); break; }
case pcode___treeview__METHOD_RepaintAlways:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_RepaintAlways(); break; }
case pcode___treeview__METHOD_Repaint:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Repaint(); break; }
case pcode___treeview__METHOD_Raise:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Raise(); break; }
case pcode___treeview__METHOD_Lower:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Lower(); break; }
case pcode___treeview__METHOD_Close:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Close(); break; }
case pcode___treeview__METHOD_Open:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_Open(); break; }
case pcode___treeview__METHOD_SetFocus:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->METHOD_SetFocus(); break; }
case pcode___treeview__SETPROPERTY_Name:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Name(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_Name:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_Name()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_Group:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Group(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_Group:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_Group()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_Background:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Background(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_Background:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_Background()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_X:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_X(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_X:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_X(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_Y:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Y(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_Y:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i =  q->GETPROPERTY_Y(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_Width:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Width(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_Width:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_Width(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_Height:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Height(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_Height:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_Height(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__GETPROPERTY_GlobalX:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_GlobalX(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__GETPROPERTY_GlobalY:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_GlobalY(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__GETPROPERTY_OldX:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_OldX(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__GETPROPERTY_OldY:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_OldY(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__GETPROPERTY_OldWidth:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_OldWidth(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__GETPROPERTY_OldHeight:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_OldHeight(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_MinimumWidth:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_MinimumWidth(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_MinimumWidth:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i =  q->GETPROPERTY_MinimumWidth(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_MinimumHeight:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_MinimumHeight(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_MinimumHeight:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i =  q->GETPROPERTY_MinimumHeight(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_MaximumWidth:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_MaximumWidth(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_MaximumWidth:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i =  q->GETPROPERTY_MaximumWidth(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_MaximumHeight:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_MaximumHeight(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_MaximumHeight:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i =  q->GETPROPERTY_MaximumHeight(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_Tag:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Tag(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_Tag:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_Tag()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_CSV:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_CSV(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_CSV:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_CSV()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_ParentForm:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_ParentForm(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_ParentForm:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_ParentForm()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_ParentControl:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_ParentControl(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_ParentControl:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_ParentControl()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_DragDrop:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_DragDrop(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_ParentControl1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_ParentControl()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_ControlType:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_ControlType(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_ControlType:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_ControlType()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_Focus:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Focus(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_Focus:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); b = q->GETPROPERTY_Focus(); if (bReturn) pushStackBoolean(b); break; }
case pcode___treeview__SETPROPERTY_FocusPolicy:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FocusPolicy(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_FocusPolicy:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_FocusPolicy()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_FocusProxy:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FocusProxy(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_FocusProxy:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_FocusProxy()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_FocusOrder:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FocusOrder(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_FocusOrder:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_FocusOrder(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_Cursor:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Cursor(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_Cursor:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_Cursor()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_FontName:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FontName(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_FontName:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_FontName()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_FontSize:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FontSize(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_FontSize:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_FontSize(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_FontItalic:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FontItalic(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_FontItalic:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); b = q->GETPROPERTY_FontItalic(); if (bReturn) pushStackBoolean(b); break; }
case pcode___treeview__SETPROPERTY_FontBold:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FontBold(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_FontBold:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); b = q->GETPROPERTY_FontBold(); if (bReturn) pushStackBoolean(b); break; }
case pcode___treeview__SETPROPERTY_FontUnderline:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FontUnderline(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_FontUnderline:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); b = q->GETPROPERTY_FontUnderline(); if (bReturn) pushStackBoolean(b); break; }
case pcode___treeview__SETPROPERTY_FontColor:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_FontColor(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_FontColor:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_FontColor()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_Enabled:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Enabled(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_Enabled:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); b = q->GETPROPERTY_Enabled(); if (bReturn) pushStackBoolean(b); break; }
case pcode___treeview__SETPROPERTY_Visible:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Visible(v[0]->tot_boolean()); break; }
case pcode___treeview__GETPROPERTY_Visible:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); b = q->GETPROPERTY_Visible(); if (bReturn) pushStackBoolean(b); break; }
case pcode___treeview__SETPROPERTY_StatusTip:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_StatusTip(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_StatusTip:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_StatusTip()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_ToolTip:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_ToolTip(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_ToolTip:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_ToolTip()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_StyleSheet:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_StyleSheet(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_StyleSheet:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_StyleSheet()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_WhatsThis:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_WhatsThis(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_WhatsThis:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_WhatsThis()); if (bReturn) pushStack(p); else delete p; break; }
case pcode___treeview__SETPROPERTY_TimerInterval:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_TimerInterval(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_TimerInterval:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_TimerInterval(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_Opacity:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_Opacity(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_Opacity:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_Opacity(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_BoxIndex:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_BoxIndex(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_BoxIndex:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_BoxIndex(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_SplitIndex:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_SplitIndex(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_SplitIndex:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_SplitIndex(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_TabIndex:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_TabIndex(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_TabIndex:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_TabIndex(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_BoxX:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_BoxX(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_BoxX:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_BoxX(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_BoxY:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_BoxY(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_BoxY:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_BoxY(); if (bReturn) pushStackInteger(i); break; }
case pcode___treeview__SETPROPERTY_ParentIndex:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_ParentIndex(v[0]->tot_integer()); break; }
case pcode___treeview__GETPROPERTY_ParentIndex:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); i = q->GETPROPERTY_ParentIndex(); if (bReturn) pushStackInteger(i); else delete p; break; }
case pcode___treeview__SETPROPERTY_ControlType1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); q->SETPROPERTY_ControlType(v[0]->toQString()); break; }
case pcode___treeview__GETPROPERTY_ControlType1:{ getParam(v, m, n); identifier = popStack(); kb_treeview *q = (kb_treeview *) identifier->to_treeview(); interpreter_parameter *p = new interpreter_parameter( q->GETPROPERTY_ControlType()); if (bReturn) pushStack(p); else delete p; break; }
