
new_class(pcode___treeview, pcode___control, 0); 

new_method(true, pcode___treeview, pcode___treeview___treeview1, pcode___treeview);

	 new_param("YesNo", pcode__BOOLEAN, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_MouseTracking, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_MouseTracking, pcode__BOOLEAN);


new_method(true, pcode___treeview, pcode___treeview__EVENT_OnSingleShot, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnEnabled, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnDisabled, pcode__VOID, false, false, false, true);


	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_CursorAnimation, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_CursorAnimation, pcode__QString);

new_method(true, pcode___treeview, pcode___treeview__METHOD_DataIds, pcode___strings);
	 
	 new_param("Id", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataRemove, pcode__VOID);
	 
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataRemoveAll, pcode__VOID);
	 
	 new_param("Id", pcode__QString, false);
	 new_param("Value", pcode__BOOLEAN, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataSetBoolean, pcode__VOID);
	 
	 new_param("Id", pcode__QString, false);
	 new_param("Value", pcode__INTEGER, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataSetInteger, pcode__VOID);
	 
	 new_param("Id", pcode__QString, false);
	 new_param("Value", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataSetString, pcode__VOID);
	 
	 new_param("Id", pcode__QString, false);
	 new_param("Value", pcode__DOUBLE, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataSetDouble, pcode__VOID);


	 new_param("Id", pcode__QString, false);
	 new_param("Value", pcode__LONG, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataSetLong, pcode__VOID);
	 
   new_param("Id", pcode__QString, false);
	 new_param("Value", pcode__CURRENCY, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataSetDecimal, pcode__VOID);
	 
	 new_param("Id", pcode__QString, false);
	 new_param("Value", pcode__DATE, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataSetDateTime, pcode__VOID);
	

	 new_param("Id", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataBoolean, pcode__BOOLEAN);
	 
	 new_param("Id", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataInteger, pcode__INTEGER);
	 
	 new_param("Id", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataString, pcode__QString);
	 
	 new_param("Id", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataDouble, pcode__DOUBLE);
	  
	 new_param("Id", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataLong, pcode__LONG);

	 new_param("Id", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataDecimal, pcode__CURRENCY);
	 
	 new_param("Id", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_DataDateTime, pcode__DATE);
	 

new_method(true, pcode___treeview, pcode___treeview__METHOD_ClearFocus, pcode__VOID);

new_method(true, pcode___treeview, pcode___treeview__METHOD_ToggleVisible, pcode__VOID);

	 new_param("Milliseconds", pcode__INTEGER, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SingleShot, pcode__VOID);
	 
new_method(true, pcode___treeview, pcode___treeview__METHOD_StartTimer, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_StopTimer, pcode__VOID);
	 
	 new_param("LocalX", pcode__INTEGER, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_GlobalX, pcode__INTEGER);
	 
	 new_param("LocalY", pcode__INTEGER, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_GlobalY, pcode__INTEGER);	 

	 new_param("GlobalX", pcode__INTEGER, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_LocalX, pcode__INTEGER);
	 
	 new_param("GlobalY", pcode__INTEGER, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_LocalY, pcode__INTEGER);
	 
new_method(true, pcode___treeview, pcode___treeview__METHOD_UnderMouse, pcode__BOOLEAN);


	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Mask, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Mask, pcode__QString);

   new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_SoundOnEvent, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_SoundOnEvent, pcode__QString);

   new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Left, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Left, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Top, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Top, pcode__t_integer);

   new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_LocalX, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_LocalX, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_LocalY, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_LocalY, pcode__t_integer);

	 new_param("n", pcode__BOOLEAN, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_DrawOnPaint, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_DrawOnPaint, pcode__BOOLEAN);


	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Palette, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Palette, pcode__QString);


	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_BackgroundStyle, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_BackgroundStyle, pcode__QString);



	 new_param("n", pcode__BOOLEAN, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_RootIsDecorated, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_RootIsDecorated, pcode__QString);

	 new_param("f", pcode___form, false);
new_method(true, pcode___treeview, pcode___treeview___treeview, pcode___treeview);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_SelectionMode, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_SelectionMode, pcode__QString);
	 new_param("n", pcode__t_boolean, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_AlternatingRowColors, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_AlternatingRowColors, pcode__t_boolean);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnEvent, pcode__VOID, false, false, false, true);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_AppendChild, pcode__t_long);
	 new_param("Icon", pcode__QString, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_AppendChild1, pcode__t_long);
	 new_param("Id", pcode__t_long, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_AppendChild2, pcode__t_long);
	 new_param("Id", pcode__t_long, false);
	 new_param("Icon", pcode__QString, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_AppendChild3, pcode__t_long);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ChildCount, pcode__t_integer);
	 new_param("Id", pcode__t_long, false);
	 new_param("Index", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Child, pcode__t_long);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Tag, pcode__QString);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
	 new_param("Tag", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetTag, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_CheckState, pcode__QString);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
	 new_param("CheckState", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetCheckState, pcode__VOID);

	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Data, pcode__t_long);

	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Flag, pcode__QString);
	 new_param("Id", pcode__t_long, false);
	 new_param("Flag", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetFlag, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__INTEGER, false);
	 new_param("ColorId", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetBackground, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__INTEGER, false);
	 new_param("ColorId", pcode__QString, false);
	 new_param("BrushStyle", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetBackground1, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__INTEGER, false);
	 new_param("ColorId", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetFontColor, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__INTEGER, false);
	 new_param("ColorId", pcode__QString, false);
	 new_param("BrushStyle", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetFontColor1, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
	 new_param("FontId", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetFont, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Caption, pcode__QString);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetCaption, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
	 new_param("Icon", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetIcon, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("ChildId", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IndexOfChild, pcode__t_integer);
	 new_param("Id", pcode__t_long, false);
	 new_param("Index", pcode__t_integer, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_InsertChild, pcode__t_integer);
	 new_param("Id", pcode__t_long, false);
	 new_param("Index", pcode__t_integer, false);
	 new_param("Icon", pcode__QString, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_InsertChild1, pcode__t_integer);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IsExpanded, pcode__t_boolean);
	 new_param("Id", pcode__t_long, false);
	 new_param("IsExpanded", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetExpanded, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IsHidden, pcode__t_boolean);
	 new_param("Id", pcode__t_long, false);
	 new_param("IsHidden", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetHidden, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IsSelected, pcode__t_boolean);
	 new_param("Id", pcode__t_long, false);
	 new_param("IsSelected", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetSelected, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_StatusTip, pcode__QString);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
	 new_param("StatusTip", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetStatusTip, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ToolTip, pcode__QString);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
	 new_param("ToolTip", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetToolTip, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Index", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_RemoveChild, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_TextAlignment, pcode__QString);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
	 new_param("TextAlignment", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetTextAlignment, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ColumnCount, pcode__t_integer);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Append, pcode__t_long);
	 new_param("Icon", pcode__QString, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Append1, pcode__t_long);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ClosePersistentEditor, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ColumnCount1, pcode__t_integer);
new_method(true, pcode___treeview, pcode___treeview__METHOD_CurrentColumn, pcode__t_integer);
new_method(true, pcode___treeview, pcode___treeview__METHOD_CurrentItem, pcode__t_long);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_EditItem, pcode__VOID);
	 new_param("Caption", pcode__QString, false);
	 new_param("Flag", pcode__QString, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_FindItem, pcode__t_long);
new_method(true, pcode___treeview, pcode___treeview__METHOD_HeaderItem, pcode__t_long);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IndexOfTopLevelItem, pcode__t_integer);
	 new_param("Index", pcode__t_integer, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Insert, pcode__t_long);
	 new_param("Index", pcode__t_integer, false);
	 new_param("Icon", pcode__QString, false);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Insert1, pcode__t_long);
new_method(true, pcode___treeview, pcode___treeview__METHOD_InvisibleRootItem, pcode__t_long);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ItemAt, pcode__t_long);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_OpenPersistentEditor, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_FirstSelectedItem, pcode__t_long);
new_method(true, pcode___treeview, pcode___treeview__METHOD_NextSelectedItem, pcode__t_long);
	 new_param("Count", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetColumnCount, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetCurrentItem, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetCurrentItem1, pcode__VOID);
	 new_param("Caption", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetHeaderLabel, pcode__VOID);
	 new_param("Caption", pcode__QString, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetHeaderLabel1, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SortColumn, pcode__t_integer);
	 new_param("Column", pcode__t_integer, false);
	 new_param("Descending", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SortItems, pcode__VOID);
	 new_param("Index", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_RemoveTopLevelItem, pcode__VOID);
	 new_param("Index", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_TopLevelItem, pcode__t_long);
new_method(true, pcode___treeview, pcode___treeview__METHOD_TopLevelItemCount, pcode__t_integer);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IsColumnHidden, pcode__t_boolean);
	 new_param("Column", pcode__t_integer, false);
	 new_param("IsColumnHidden", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetColumnHidden, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IsSortingEnabled, pcode__t_boolean);
	 new_param("IsSortingEnabled", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetSortingEnabled, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IsItemsExpandable, pcode__t_boolean);
	 new_param("IsItemsExpandable", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetItemsExpandable, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IsAllColumnsShowFocus, pcode__t_boolean);
	 new_param("IsAllColumnsShowFocus", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetAllColumnsShowFocus, pcode__VOID);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ColumnWidth, pcode__t_integer);
	 new_param("Column", pcode__t_integer, false);
	 new_param("Width", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetColumnWidth, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_CollapseAll, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ExpandAll, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SelectAll, pcode__VOID);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ShowColumn, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_CollapseItem, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ExpandItem, pcode__VOID);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ScrollToItem, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_IsAlternatingRowColors, pcode__t_boolean);
	 new_param("IsAlternatingRowColors", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetAlternatingRowColors, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ScrollToBottom, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_ScrollToTop, pcode__VOID);
	 new_param("Current", pcode__t_long, false);
	 new_param("Previous", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_CurrentItemChanged, pcode__VOID, false, false, false, true);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemActivated, pcode__VOID, false, false, false, true);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemChanged, pcode__VOID, false, false, false, true);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemClicked, pcode__VOID, false, false, false, true);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemCollapsed, pcode__VOID, false, false, false, true);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemDoubleClicked, pcode__VOID, false, false, false, true);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemEntered, pcode__VOID, false, false, false, true);
	 new_param("Id", pcode__t_long, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemExpanded, pcode__VOID, false, false, false, true);
	 new_param("Id", pcode__t_long, false);
	 new_param("Column", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemPressed, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_ItemSelectionChanged, pcode__VOID, false, false, false, true);




    new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Layout, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Layout, pcode__QString);

	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Move, pcode__VOID);
	 new_param("Width", pcode__t_integer, false);
	 new_param("Height", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Resize, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Show, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Hide, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_RepaintAlways, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Repaint, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Raise, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Lower, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Close, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_Open, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__METHOD_SetFocus, pcode__VOID);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Name, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Name, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Group, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Group, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Background, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Background, pcode__QString);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_X, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_X, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Y, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Y, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Width, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Width, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Height, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Height, pcode__t_integer);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_GlobalX, pcode__t_integer);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_GlobalY, pcode__t_integer);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_OldX, pcode__t_integer);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_OldY, pcode__t_integer);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_OldWidth, pcode__t_integer);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_OldHeight, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_MinimumWidth, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_MinimumWidth, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_MinimumHeight, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_MinimumHeight, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_MaximumWidth, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_MaximumWidth, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_MaximumHeight, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_MaximumHeight, pcode__t_integer);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Tag, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Tag, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_CSV, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_CSV, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_ParentForm, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_ParentForm, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_ParentControl, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_ParentControl, pcode__QString);
	 new_param("n", pcode__t_boolean, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_DragDrop, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__GETPROPERTY_ParentControl1, pcode__t_boolean);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_ControlType, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_ControlType, pcode__QString);
	 new_param("n", pcode__t_boolean, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Focus, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Focus, pcode__t_boolean);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FocusPolicy, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FocusPolicy, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FocusProxy, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FocusProxy, pcode__QString);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FocusOrder, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FocusOrder, pcode__t_integer);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Cursor, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Cursor, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FontName, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FontName, pcode__QString);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FontSize, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FontSize, pcode__t_integer);
	 new_param("n", pcode__t_boolean, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FontItalic, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FontItalic, pcode__t_boolean);
	 new_param("n", pcode__t_boolean, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FontBold, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FontBold, pcode__t_boolean);
	 new_param("n", pcode__t_boolean, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FontUnderline, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FontUnderline, pcode__t_boolean);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_FontColor, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_FontColor, pcode__QString);
	 new_param("n", pcode__t_boolean, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Enabled, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Enabled, pcode__t_boolean);
	 new_param("n", pcode__t_boolean, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Visible, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Visible, pcode__t_boolean);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_StatusTip, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_StatusTip, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_ToolTip, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_ToolTip, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_StyleSheet, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_StyleSheet, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_WhatsThis, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_WhatsThis, pcode__QString);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_TimerInterval, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_TimerInterval, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_Opacity, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_Opacity, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_BoxIndex, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_BoxIndex, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_SplitIndex, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_SplitIndex, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_TabIndex, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_TabIndex, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_BoxX, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_BoxX, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_BoxY, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_BoxY, pcode__t_integer);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_ParentIndex, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_ParentIndex, pcode__t_integer);
	 new_param("n", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__SETPROPERTY_ControlType1, pcode__VOID);
new_method(true, pcode___treeview, pcode___treeview__GETPROPERTY_ControlType1, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_SQLName, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_SQLName, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_SQLType, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_SQLType, pcode__QString);
	 new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_SQLCaption, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_SQLCaption, pcode__QString);
	 new_param("n", pcode__t_integer, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_SQLWidth, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_SQLWidth, pcode__t_integer);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnOpen, pcode__VOID, false, false, false, true);
	 new_param("Cancel", pcode__BOOLEAN_POINTER, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnClose, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnContextMenu, pcode__BOOLEAN, false, false, false, true);
	 new_param("Cancel", pcode__t_boolean, false);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
	 new_param("Width", pcode__t_integer, false);
	 new_param("Height", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnDragEnter, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnDragExit, pcode__VOID, false, false, false, true);
	 new_param("Cancel", pcode__t_boolean, false);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
	 new_param("Width", pcode__t_integer, false);
	 new_param("Height", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnDragMove, pcode__VOID, false, false, false, true);
	 new_param("Cancel", pcode__t_boolean, false);
	 new_param("MimeData", pcode__QString, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnDrop, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnEnter, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnGotFocus, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnLostFocus, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnHide, pcode__VOID, false, false, false, true);
	 new_param("Key", pcode__t_integer, false);
	 new_param("Shift", pcode__t_boolean, false);
	 new_param("Control", pcode__t_boolean, false);
	 new_param("Alt", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnKeyDown, pcode__VOID, false, false, false, true);
	 new_param("Key", pcode__t_integer, false);
	 new_param("Shift", pcode__t_boolean, false);
	 new_param("Control", pcode__t_boolean, false);
	 new_param("Alt", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnKeyUp, pcode__VOID, false, false, false, true);
	 new_param("Key", pcode__t_integer, false);
	 new_param("Shift", pcode__t_boolean, false);
	 new_param("Control", pcode__t_boolean, false);
	 new_param("Alt", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnKeyPress, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnExit, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
	 new_param("Left", pcode__t_boolean, false);
	 new_param("Right", pcode__t_boolean, false);
	 new_param("Mid", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnDblClick, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
	 new_param("Left", pcode__t_boolean, false);
	 new_param("Right", pcode__t_boolean, false);
	 new_param("Mid", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnClick, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnMouseMove, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
	 new_param("Left", pcode__t_boolean, false);
	 new_param("Right", pcode__t_boolean, false);
	 new_param("Mid", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnMouseDown, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
	 new_param("Left", pcode__t_boolean, false);
	 new_param("Right", pcode__t_boolean, false);
	 new_param("Mid", pcode__t_boolean, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnMouseUp, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("OldX", pcode__t_integer, false);
	 new_param("OldY", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnMove, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("Width", pcode__t_integer, false);
	 new_param("Height", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnPaint, pcode__VOID, false, false, false, true);
	 new_param("Width", pcode__t_integer, false);
	 new_param("Height", pcode__t_integer, false);
	 new_param("OldWidth", pcode__t_integer, false);
	 new_param("OldHeight", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnResize, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnShow, pcode__VOID, false, false, false, true);
	 new_param("X", pcode__t_integer, false);
	 new_param("Y", pcode__t_integer, false);
	 new_param("GlobalX", pcode__t_integer, false);
	 new_param("GlobalY", pcode__t_integer, false);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnMouseWheel, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnTimer, pcode__VOID, false, false, false, true);
new_method(true, pcode___treeview, pcode___treeview__EVENT_OnPrint, pcode__VOID, false, false, false, true);


   new_param("n", pcode__QString, false);
new_property_set(pcode___treeview, pcode___treeview__SETPROPERTY_SQL, pcode__VOID);
new_property_get(pcode___treeview, pcode___treeview__GETPROPERTY_SQL, pcode__QString);
